#spring:
#  cloud:
#    gateway:
#      default-filters:
#        - AddResponseHeader=source,zhaozhong
#      routes:
#        - id: api_Route
#          uri: http://localhost:8123
#          predicates:
#            - Path=/test/api/**
#        - id: bi_Route
#          uri: http://localhost:8080
#          predicates:
#            - Path=/bi/api/**

server:
  port: 8090
dubbo:
  application:
    name: zhaozhong-OpenApi-Gateway
  protocol:
    name: tri
    port: 50052
  registry:
    address: nacos://localhost:8848